### PR TITLE
Add django 1.8 fixture

### PR DESCRIPTION
**Pull request by meshy**

### CODE REVIEW

**Comment by meshy** [comment]
Sorry this is a little late; was on holiday.

**Comment by ghickman** [comment]
@meshy – nice work :+1:

**Comment by mjtamlyn** [comment]
Awesome sauce. :fireworks:

**Comment by meshy** [comment]
Deployed.

**Comment by meshy** [comment]
...and thanks for the quick merge, @ghickman `;)`

**Pull request merged**
