### PR TITLE
Support 1.11

### PR DESCRIPTION
**Pull request by mkoistinen**
Should satisfy #116 =)

### CODE REVIEW

**Comment by mkoistinen** [comment]
So, I was hoping to also add support for the new CBVs in `django.contrib.auth`, I tried updating the `settings.CBV_SOURCES`, but wasn't able to get any success with that =/

**Comment by exonian** [comment]
This is looking great! I'll go take a look and see if I can work out what's going on with the `auth` views.

**Comment by exonian** [comment]
So the problem seems to be that some of those views have `success_url = reverse_lazy('<something>')` as the class default (so we get a `NoReverseMatch`), whereas I think everything else we've encountered has defaulted to `None`. I'm not sure yet what I think the best approach to solving this is, but I thought I'd post back now so others can start thinking about it too.

**Comment by mkoistinen** [comment]
If we're just introspecting, perhaps we can just mock the url pattern it is expecting?

**Comment by exonian** [comment]
Ha good timing: I was just this minute coming back to update after some tinkering.

That would definitely make the error go away, but I feel like we should strive to document the `reverse_lazy` call. In that regard, the uses of `gettext_lazy` will present the same problem (but without the error, as the translate will work).

For both cases, I think we may have to either use the proxy's `__reduce__` method, or maybe mock the proxy or some method on it. Although I'm not sure either of those would readily return us something like `reverse_lazy`, rather it might only get us as far as the wrapped `reverse`.

In which case maybe we have to inspect the line of code (if we can) and grab from there.

**Comment by exonian** [comment]
Can't get mocking or anything working myself yet.

The best I can do so far is detecting when it's lazy evaluation and then saying something like "if it's calling `reverse` then it was `lazy_reverse`" (plus we have the args that were passed through). This would also work for the `ugettext_lazy`/`gettext_lazy` ones. It feels super lame but it might be our best bet unless someone can get the mocking/monkeypatching thing going in a decent way.

**Comment by mkoistinen** [comment]
OK, I think I've licked this. No need for fancy Mock()'ing at all, just plain-ole duck-typing =)

**Comment by exonian** [comment]
I've opened #119 based on this because I wanted to try taking it in a slightly different direction. It feels neater to me, but let me know your thoughts.

**Comment by exonian** [comment]
@mkoistinen Alright if I close this one if we're going with #119 instead?

**Pull request closed without merging**
