### PR TITLE
Multiple targets

### PR DESCRIPTION
**Pull request by exonian**
Adds support for multiple "sources" of CBVs. Implemented as a dict in settings rather than its own model, which is maybe a bit of a cut corner but should be fine.

Importer seems to work just fine, docs url generator too. Had to do some work on the navbar (which I'm pretty happy with) and the homepage/version pages (less so) to account for single-part module names being pretty confusing now they're not all siblings.

Fixtures regenerated for 1.9, to include the new `contrib.auth` mixins
Fixtures not regenerated for versions which contain `contrib.formtools` (<1.8) but if anybody wants these then it's pretty straightforward

Stopped generating djangoproject.com docs urls for <1.7 as they don't host those docs any more.

Upgraded to Django 1.8. Discarded the South migrations and generated a new initial Django migration. Didn't make any schema changes, so `manage.py migrate cbv --fake` should work fine for all installs which had run all the South migrations.

Partially addresses #89; addresses #91, #103 and #104

### CODE REVIEW

**Comment by mjtamlyn** [comment]
Can you still compile old versions with that setting or will it blow up?

**Comment by exonian** [comment]
It catches `ImportError` and ignores it, so it works with versions that don't have `auth.mixins`. I developed locally on 1.5 before I upgraded, I just didn't feel like regenerating fixtures for all the old versions.

In fact, I've currently got it set with both `contrib.auth.mixins` and `contrib.formtools.wizard.views` (which have never been in the same version), so it's always quietly ignoring at least one.

**Comment by ghickman** [comment]
Looks good! Could you add some screenshots for the visual changes?

**Comment by exonian** [comment]
selection_026
Sources are included in the navbar, with a divider between the last dropdown of a source and the name of the next source; modules with only one klass just have a link to the klass instead of a dropdown.

selection_027
Module names are prepended with the source name unless that would do something like "Generic generic" (ie the `__init__.py` of generic views) in which case we squash it back to just the one bit. Experimented with having a "Generic" section and then just "base", "detail" et al under that, ie what we had before but just multiple sets of it, but it looked ever weirder.

**Comment by meshy** [comment]
I don't think `GenericViewError` should be in there...

**Comment by meshy** [comment]
My bad -- I'm wrong!

**Comment by meshy** [comment]
@exonian thanks for this!

> Experimented with having a "Generic" section and then just "base", "detail" et al under that

Perhaps that's one for another PR.

**Comment by mjtamlyn** [comment]
Looks pretty good to me

**Comment by exonian** [comment]
Yeah `GenericViewError` used to be the only member of the `Generic` dropdown so it was a choice between finding a sensible name for that dropdown and just putting it up there. At least now I don't waste a click on it! :smile: 

>Perhaps that's one for another PR.
:+1: :100:

**Comment by ghickman** [comment]
@exonian – nice work on the navbar layout!

@meshy – 👍  to merging from me.

**Comment by meshy** [comment]
Oops! I think we should update the old json files before pushing live so that we can get it on as many versions as possible. @exonian are you able to update the old files to include this new stuff?

**Comment by exonian** [comment]
@meshy: As in `contrib.formtools.wizard` for versions up to 1.7? Can do, yeah, maybe this evening. Are we still supporting back as far as 1.3?

**Comment by meshy** [comment]
@exonian yeah, I think we should continue to support django 1.3+ -- I suspect `django.contrib.formtools.wizard.views.WizardView` is newer than that though.


That'd be awesome, thank you!

**Comment by exonian** [comment]
No problem. Looks like it landed in 1.4, so only four sets of fixtures to make ;)

**Pull request merged**
