### PR TITLE
Django 1.10 fixtures

### PR DESCRIPTION
**Pull request by exonian**

### CODE REVIEW

**Comment by meshy** [comment]
Blatherwick, you're a wonder.

**Comment by exonian** [comment]
I misread that at first and thought "bit harsh"
Although I'm pretty sure the ~~bug~~ extreme shortsightedness was mine too anyway :)

**Comment by meshy** [comment]
haha not meant to be harsh at all! I really appreciate you digging into this to fix it!

**Comment by meshy** [comment]
Fixes #109

**Comment by meshy** [comment]
:+1: LGTM, HWTI

**Comment by ghickman** [comment]
@meshy – I can't deploy this until later this evening, however feel free to pick it up before me if you've got the time!

**Pull request merged**
