### PR TITLE
Run export for django 2.1

### PR DESCRIPTION
**Pull request by meshy**
Could someone load this fixture and sanity-check it for me?

Hopefully I'll be able to push this to the server in the morning.

### CODE REVIEW

**Comment by ghickman** [comment]
@meshy – can you replace Opbeat with Sentry (in a seperate PR would be ace…)? I know Opbeat has gone away but it would be great to have Sentry in its place when we do a deploy!

**Comment by meshy** [comment]
Sounds like a good plan to me :)

**Comment by meshy** [comment]
It's probably worth considering getting #135 sorted before continuing with this.

**Comment by meshy** [comment]
I've rebased this with a new dump based on the fixes from #135.

**Pull request merged**
