### PR TITLE
Django 2.0

### PR DESCRIPTION
**Pull request by meshy**
I probably went a little overboard here, but given django 2.0 support is rather late, I thought I might as well get it all done in one go. The commits should be fairly safe to review one-at-a-time, but here's the most important things:

- **Upgraded to Python 3.6.** I've gone crazy on f-strings. The novelty will wear off one day, I expect.
- **Upgraded to Django 2.0.** This was required to get the import working, and is a nice-to-have.
- **Removed unused `Function` model.** We were populating a model, but then not displaying the contents. Upgrading to 3.6 broke this, so it was easiest to just remove it.
- **Added a JSON dump for Django 2.0.** `\o/`

### CODE REVIEW

**Comment by exonian** [comment]
This is fantastic!

The only other thing I caught when I did my Python 3 branch (and I didn't do a whole load that you did!) was adding `'__spec__'` to `banned_attr_names` in `populate_cbv.py`

**Comment by exonian** [comment]
It would also be good if we could get the decorated methods work in while we're generating the 2.0 fixtures

I know I had it working on Python 2 (though no idea if it'll be a painless transition to 3 or not tbh) but I didn't merge it at the time because I hadn't got around to going and generating all the old fixtures with it.

https://github.com/refreshoxford/django-cbv-inspector/compare/feature/decorated-methods

**Comment by ghickman** [comment]
LGTM.

I'd say avoid adding the decorated methods to this PR lest we muddy the waters of a pure upgrade with a fix/feature.

**Comment by exonian** [comment]
Yeah good point. Just the `__spec__` thing then

**Comment by meshy** [comment]
Thanks @exonian and @ghickman.

I've added `__spec__` to the banned attributes, and have re-created the JSON. I've also added a migration I had forgotten.

The decorators are an important point, but you're right, it's probably best to do that in another PR.

**Comment by meshy** [comment]
Ah. So I've deployed it. Hm. Crap. The static isn't working. 2250hrs was not the smartest time for a deploy.

**Comment by meshy** [comment]
I downgraded the version of django, and that seems to have sorted locally, but when I pushed it, it still doesn't work. 47531fa

**Comment by meshy** [comment]
I needed to change an env var for some reason...

https://github.com/heroku/heroku-buildpack-python/issues/457#issuecomment-373559535

**Pull request merged**
